a:3:{i:0;a:16:{s:4:"e_id";s:3:"174";s:10:"e_admin_id";s:1:"3";s:7:"e_title";s:80:"[미탐] 페이첵스 예상 EPS 0.66 (12월 4째주 주요 실적발표 기업)";s:9:"e_content";s:882:"&quot;이번주..페이첵스가&nbsp;실적발표&nbsp;한다던데..?&quot;<br />
<br />
#이번주실적발표는어디&nbsp;#실적보고<br />
　<br />
기업의&nbsp;시작과&nbsp;끝인&nbsp;&lsquo;실적발표&rsquo;<br />
미국&nbsp;주식에서&nbsp;실적을&nbsp;봐야&nbsp;하는&nbsp;이유입니다.<br />
　<br />
미.탐이가&nbsp;초이스한&nbsp;매력적인&nbsp;종목은?<br />
　<br />
12월&nbsp;4째주&nbsp;어떤&nbsp;기업이&nbsp;실적&nbsp;발표를&nbsp;할까요?<br />
&nbsp;
<hr /><br />
여러분, 메리 크리스마스 :)&nbsp;<br />
&nbsp;
<hr /><br />
<br />
<img alt="" src="/webdata/attach_data/explore/202012/0622f2b9bf85fea224d2288cd2f8f7da.png" style="height:788px; width:940px" /><br />
<br />
미국주식투자 이야기를 만나보세요.<br />
- 인스타그램 @_usstock<br />
- 네이버포스트 @dataheros<br />
&nbsp;";s:14:"e_display_date";s:19:"2020-12-21 08:00:00";s:12:"e_view_count";s:3:"207";s:11:"e_is_active";s:3:"YES";s:11:"e_thumbnail";s:72:"/webdata/attach_data/explore/202012/0622f2b9bf85fea224d2288cd2f8f7da.png";s:6:"e_push";s:1:"Y";s:10:"e_view_srv";s:0:"";s:10:"e_push_srv";s:1:"A";s:5:"e_pay";s:1:"N";s:11:"e_is_inside";s:1:"N";s:12:"e_kiwoom_off";s:0:"";s:12:"e_created_at";s:19:"2020-12-17 10:44:21";s:12:"e_updated_at";s:19:"2020-12-17 10:44:21";}i:1;a:16:{s:4:"e_id";s:3:"173";s:10:"e_admin_id";s:1:"3";s:7:"e_title";s:57:"코카콜라, 너로 정했다 (feat. 미국기업소개)";s:9:"e_content";s:1594:"미국주식의&nbsp;세계에&nbsp;잘&nbsp;왔다!<br />
<br />
가랏!&nbsp;오늘은&nbsp;코카콜라<br />
너로&nbsp;정했다!<br />
<br />
투자매력점수&nbsp;71점,&nbsp;안볼거야~&nbsp;?<br />
<br />
애플&nbsp;테슬라&nbsp;나이키&nbsp;아마존<br />
페이스북&nbsp;디즈니&nbsp;비자&nbsp;넷플릭스<br />
서로&nbsp;생긴&nbsp;티커는&nbsp;달라도&nbsp;우리는&nbsp;모두&nbsp;미국주식!<br />
<br />
#포켓몬스터추억잼&nbsp;#미국기업소개<br />
<br />
<img alt="" src="/webdata/attach_data/explore/202012/6a6ea95bd95d4119391656631edc9845.png" style="height:788px; width:940px" /><img alt="" src="/webdata/attach_data/explore/202012/2dc961702c7f9f1b167228d477c1ad8b.png" style="height:788px; width:940px" /><img alt="" src="/webdata/attach_data/explore/202012/d728842e6d9fadc6600db0c988061d15.png" style="height:788px; width:940px" /><img alt="" src="/webdata/attach_data/explore/202012/b87a0415cb3de7b94577cfeb8baeb15f.png" style="height:788px; width:940px" /><img alt="" src="/webdata/attach_data/explore/202012/3542e1678b3a6e2c6f653100d7a6f95e.png" style="height:788px; width:940px" /><img alt="" src="/webdata/attach_data/explore/202012/5e007fe9338f0e10adeecbd84ab9d1ab.png" style="height:788px; width:940px" /><br />
*해당&nbsp;콘텐츠는&nbsp;다양한&nbsp;미국기업을&nbsp;소개하는&nbsp;콘텐츠로&nbsp;참고용으로만&nbsp;봐주시길&nbsp;바랍니다.<br />
<br />
<br />
미국주식투자 이야기를 만나보세요.<br />
- 인스타그램 @_usstock<br />
- 네이버포스트 @dataheros<br />
&nbsp;";s:14:"e_display_date";s:19:"2020-12-17 08:00:00";s:12:"e_view_count";s:3:"486";s:11:"e_is_active";s:3:"YES";s:11:"e_thumbnail";s:72:"/webdata/attach_data/explore/202012/6a6ea95bd95d4119391656631edc9845.png";s:6:"e_push";s:1:"Y";s:10:"e_view_srv";s:0:"";s:10:"e_push_srv";s:1:"A";s:5:"e_pay";s:1:"N";s:11:"e_is_inside";s:1:"N";s:12:"e_kiwoom_off";s:0:"";s:12:"e_created_at";s:19:"2020-12-16 14:29:53";s:12:"e_updated_at";s:19:"2020-12-16 14:29:53";}i:2;a:16:{s:4:"e_id";s:3:"172";s:10:"e_admin_id";s:1:"3";s:7:"e_title";s:68:"나이키 예상 EPS 0.61 (12월 3째주 주요 실적발표 기업)";s:9:"e_content";s:790:"&quot;이번주..나이키가&nbsp;실적발표&nbsp;한다던데..?&quot;<br />
<br />
#이번주실적발표는어디&nbsp;#실적보고<br />
　<br />
기업의&nbsp;시작과&nbsp;끝인&nbsp;&lsquo;실적발표&rsquo;<br />
미국&nbsp;주식에서&nbsp;실적을&nbsp;봐야&nbsp;하는&nbsp;이유입니다.<br />
　<br />
미.탐이가&nbsp;초이스한&nbsp;매력적인&nbsp;종목은?<br />
　<br />
12월&nbsp;3째주&nbsp;어떤&nbsp;기업이&nbsp;실적&nbsp;발표를&nbsp;할까요?<br />
<br />
<img alt="" src="/webdata/attach_data/explore/202012/9e787a5aef9cbabeb55984cce22046ec.png" style="height:788px; width:940px" /><br />
<br />
미국주식투자 이야기를 만나보세요.<br />
- 인스타그램 @_usstock<br />
- 네이버포스트 @dataheros<br />
&nbsp;";s:14:"e_display_date";s:19:"2020-12-14 12:30:00";s:12:"e_view_count";s:3:"565";s:11:"e_is_active";s:3:"YES";s:11:"e_thumbnail";s:72:"/webdata/attach_data/explore/202012/9e787a5aef9cbabeb55984cce22046ec.png";s:6:"e_push";s:1:"Y";s:10:"e_view_srv";s:0:"";s:10:"e_push_srv";s:1:"A";s:5:"e_pay";s:1:"N";s:11:"e_is_inside";s:1:"N";s:12:"e_kiwoom_off";s:0:"";s:12:"e_created_at";s:19:"2020-12-11 10:14:53";s:12:"e_updated_at";s:19:"2020-12-11 10:19:13";}}