a:3:{i:0;a:23:{s:4:"e_id";s:4:"1043";s:10:"e_admin_id";s:1:"3";s:7:"e_title";s:76:"[모닝브리핑] 오미크론 변이·긴축 우려로 美 증시 하락세";s:9:"e_content";s:2047:"■ 미국 증시 브리핑
- 다우존스 : 35,365.44 (▽532.2 -1.48%)
- 나스닥 : 15,169.68 (▽10.75 -0.07%)
- S&P500 : 4,620.64 (▽48.03 -1.03%)

■ 포트폴리오 수익률 : +43.42% (▽3.2%P, 전주 대비)
☞ 홈 > 추천 > 포트폴리오에서 확인할 수 있습니다.
https://www.choicestock.co.kr/stock/recommend/portfolio

■ 포트 편입종목 수익률 TOP 5
- 마이크로소프트 +115.01%
- 로우스컴퍼니 +61.23%
- 메타 플랫폼스 +39.78%
- 써모피셔 +33.69%
- 애플 +30.64%

■ 추천종목 강세주
- 에드워즈라이프사이언시스(EW) +2.13%, 누적 수익률 +8.07%
- 인사이트(INCY) +1.24%, 누적 수익률 +7.19%
- 애보트래버러토리(ABT) 52주최고가, 누적 수익률 +14.26%
- 시스코 시스템즈(CSCO) 52주최고가, 누적 수익률 +2.47%

■ 추천종목 주요뉴스
- 나이키(NKE), 오늘 2분기 실적 발표 예정
- 로우스 컴퍼니스(LOW), 프리미엄 정당화되는 사업 성장세 예상, 목표가 275달러 → 300달러로 상향 (Guggenheim)
- 어도비(ADBE), 보수적 가이던스에 주가 하락했지만 수요는 견고해, 투자의견 매수 유지, 목표가 750달러 → 700달러로 하향 (스티펄)
- 애플(AAPL), 무선 칩 자체 제작 위한 팀 구성 중 (시킹알파)
- 알파벳(GOOGL), '사이드워크 랩스' 프로젝트 구글로 편입 예정
- 제너럴 모터스(GM), 크루즈 자율주행 사업부문 CEO 사임

■ 최근 추천종목
- 시스코 시스템즈 (CSCO), 몬스터베버리지(MNST), 넷플릭스(NFLX)

■ 전일 추천, 편출종목 : 없음

■ 오늘 배당락 예정 종목
- 옴니컴(OMC) : 주당배당금 0.7 달러, 배당수익률 3.83%
- 레스토랑 브랜드 인터내셔널(QSR) : 주당배당금 0.53 달러, 배당수익률 3.69%
- 메디패스트(MED) : 주당배당금 1.42 달러, 배당수익률 2.68%
☞ 종목별 배당투자매력도 점수는 홈 > 검색을 통해 확인할 수 있습니다.

매일 밤, 투자의 즐거움을 경험하세요.
초이스스탁US";s:7:"e_class";s:1:"3";s:9:"e_tickers";s:0:"";s:14:"e_display_date";s:19:"2021-12-20 08:37:00";s:12:"e_view_count";s:3:"221";s:11:"e_is_active";s:3:"YES";s:11:"e_thumbnail";s:0:"";s:9:"e_view_cs";s:1:"Y";s:9:"e_view_wt";s:1:"Y";s:9:"e_view_st";s:1:"Y";s:9:"e_view_pe";s:1:"Y";s:9:"e_view_ws";s:1:"N";s:9:"e_view_sh";s:1:"N";s:6:"e_push";s:1:"Y";s:10:"e_view_srv";s:0:"";s:10:"e_push_srv";s:1:"Y";s:5:"e_pay";s:1:"Y";s:11:"e_is_inside";s:1:"N";s:12:"e_created_at";s:19:"2021-12-20 08:20:47";s:12:"e_updated_at";s:19:"2021-12-20 08:34:59";}i:1;a:23:{s:4:"e_id";s:4:"1042";s:10:"e_admin_id";s:1:"3";s:7:"e_title";s:64:"[시황] '네 마녀의 날' 맞아..은행·기술주 하락↓";s:9:"e_content";s:2854:"<strong>■ 미국 증시 브리핑 (12/17 마감)</strong><br />
- 다우존스 : 35,365.44 (▽532.2 -1.48%)<br />
- 나스닥 : 15,169.68 (▽10.75 -0.07%)<br />
- S&amp;P500 : 4,620.64 (▽48.03 -1.03%)<br />
<br />
<strong>■ 금일 배당락 발표기업</strong><br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/ABEV">암베브(ABEV)</a> : 주당배당금 0.023804 달러, 배당수익률 3.89%<br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/OMC">옴니컴(OMC)</a> : 주당배당금 0.7 달러, 배당수익률 3.83%<br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/QSR">레스토랑 브랜드 인터내셔널(QSR)</a> : 주당배당금 0.53 달러, 배당수익률 3.69%<br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/PLOW">더글라스 다이나믹스(PLOW)</a> : 주당배당금 0.285 달러, 배당수익률 3.02%<br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/MED">메디패스트(MED) </a>: 주당배당금 1.42 달러, 배당수익률 2.68%<br />
※ 배당수익률은 연간 기준<br />
<br />
<strong>■ 전일 급등주</strong><br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/SPRB">스프루스 바이오사이언스(SPRB)</a> : 5.03달러 (▲2.55 +102.82%)<br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/GNFT">젠피트(GNFT)</a> : 5.09달러 (▲1.79 +54.24%)<br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/BLPH">벨레로폰 쎄라퓨틱스(BLPH)</a> : 3.19달러 (▲0.82 +34.60%)<br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/AUID">입시디(AUID)</a> : 16.72달러 (▲3.59 +27.34%)<br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/IREN">아이리스 에너지(IREN)</a> : Iris Energy달러 (▲12.61 +368.00%)<br />
<br />
<strong>■ 52주 최고가 경신</strong><br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/EVTL">Vertical Aerospace Ltd(EVTL)</a> : 12.84달러 (▲2.09 +19.44%)<br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/ROIV">로이반트 사이언시스(ROIV)</a> : 10.95달러 (▲1.69 +18.25%)<br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/EPAY">바텀라인 테크놀러지스(EPAY)</a> : 56.13달러 (▲7.21 +14.74%)<br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/EBTC">엔터프라이즈 뱅코프(EBTC)</a> : 43.99달러 (▲5.15 +13.26%)<br />
- <a href="https://wowtv.choicestock.co.kr/wt_search/summary/CERN">서너(CERN)</a> : 89.77달러 (▲10.28 +12.93%)<br />
<br />
★ 미국주식창 서비스에 가입하면 <ins>추천/포트폴리오, 진단, 발굴 서비스</ins>를 모두 이용할 수 있습니다.<br />
&nbsp;&nbsp;&nbsp;<a href="https://wowtv.choicestock.co.kr/wt_main/service">☞ 지금 신청하기</a>";s:7:"e_class";s:1:"1";s:9:"e_tickers";s:0:"";s:14:"e_display_date";s:19:"2021-12-20 08:50:00";s:12:"e_view_count";s:4:"1307";s:11:"e_is_active";s:3:"YES";s:11:"e_thumbnail";s:0:"";s:9:"e_view_cs";s:1:"N";s:9:"e_view_wt";s:1:"Y";s:9:"e_view_st";s:1:"N";s:9:"e_view_pe";s:1:"N";s:9:"e_view_ws";s:1:"N";s:9:"e_view_sh";s:1:"N";s:6:"e_push";s:1:"N";s:10:"e_view_srv";s:0:"";s:10:"e_push_srv";s:1:"N";s:5:"e_pay";s:1:"N";s:11:"e_is_inside";s:1:"N";s:12:"e_created_at";s:19:"2021-12-20 08:14:21";s:12:"e_updated_at";s:19:"2021-12-20 08:14:21";}i:2;a:23:{s:4:"e_id";s:4:"1041";s:10:"e_admin_id";s:1:"3";s:7:"e_title";s:76:"[배당락] 암베브, 주당 배당금 0.0238 달러, 배당수익률 3.89%";s:9:"e_content";s:1505:"20일 배당락이 예정된 기업을 소개합니다.<br />
<br />
- 암베브(<a href="https://www.choicestock.co.kr/search/summary/ABEV">ABEV</a>) : 주당배당금 0.0238 달러, 배당수익률 3.89%<br />
- 옴니컴(<a href="https://www.choicestock.co.kr/search/summary/OMC">OMC</a>) : 주당배당금 0.7 달러, 배당수익률 3.83%<br />
<br />
- 레스토랑 브랜드 인터내셔널(<a href="https://www.choicestock.co.kr/search/summary/QSR">QSR</a>) : 주당배당금 0.53 달러, 배당수익률 3.69%<br />
- 더글라스 다이나믹스(<a href="https://www.choicestock.co.kr/search/summary/PLOW">PLOW</a>) : 주당배당금 0.285 달러, 배당수익률 3.02%<br />
<br />
- 메디패스트(<a href="https://www.choicestock.co.kr/search/summary/MED">MED</a>) : 주당배당금 1.42 달러, 배당수익률 2.68%<br />
- 카만(<a href="https://www.choicestock.co.kr/search/summary/KAMN">KAMN</a>) : 주당배당금 0.2 달러, 배당수익률 1.92%<br />
<br />
- 퀘넥스 빌딩 프로덕트(<a href="https://www.choicestock.co.kr/search/summary/NX">NX</a>) : 주당배당금 0.08 달러, 배당수익률 1.37%<br />
- SEI 인베스트먼트(<a href="https://www.choicestock.co.kr/search/summary/SEIC">SEIC</a>) : 주당배당금 0.4 달러, 배당수익률 1.28%<br />
<br />
- 오메가 플렉스(<a href="https://www.choicestock.co.kr/search/summary/OFLX">OFLX</a>) : 주당배당금 0.3 달러, 배당수익률 1.01%<br />
<br />
※ 배당수익률은 연간 기준<br />
&nbsp;";s:7:"e_class";s:1:"2";s:9:"e_tickers";s:39:"ABEV,OMC,QSR,PLOW,MED,KAMN,NX,SEIC,OFLX";s:14:"e_display_date";s:19:"2021-12-20 08:25:00";s:12:"e_view_count";s:2:"10";s:11:"e_is_active";s:3:"YES";s:11:"e_thumbnail";s:0:"";s:9:"e_view_cs";s:1:"Y";s:9:"e_view_wt";s:1:"Y";s:9:"e_view_st";s:1:"Y";s:9:"e_view_pe";s:1:"Y";s:9:"e_view_ws";s:1:"N";s:9:"e_view_sh";s:1:"N";s:6:"e_push";s:1:"N";s:10:"e_view_srv";s:0:"";s:10:"e_push_srv";s:1:"N";s:5:"e_pay";s:1:"N";s:11:"e_is_inside";s:1:"N";s:12:"e_created_at";s:19:"2021-12-20 08:04:08";s:12:"e_updated_at";s:19:"2021-12-20 08:27:51";}}